name: CI Workflow

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Checkout repository"

      - name: "Install dependencies"
      - run: npm install

      - name: "Run Tests"
      - run: npm run test
